library(RobustRankAggreg)
a=read.table("GSE7904.txt",header=T,sep = '\t',quote = '')
b=read.table("GSE65194.txt",header=T,sep = '\t',quote = '')
c=read.table("GSE45827.txt",header=T,sep = '\t',quote = '')
d=read.table("GSE22820.txt",header=T,sep = '\t',quote = '')
glist <- list(a[,1], b[,1], c[,1], d[,1])
r = rankMatrix(glist, full = TRUE)
head(r)
aggregateRanks(rmat = r, method = "RRA")
